[package]
name = "neorg-breeze"
description = "A library for parsing entire directories of Norg files in a multithreaded fashion."
repository = "https://github.com/nvim-neorg/neorg-breeze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
neorg-dirman = "0.1.0"
threadpool = "1.8.1"
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter" }
tree-sitter-norg = { git = "https://github.com/nvim-neorg/tree-sitter-norg2" }
